### PR TITLE
ensure support for python 3.4 and 3.7 respectively.

### PR DESCRIPTION
**Pull request by nazrulworld**
* setuptools version upgraded in requirements.txt file to work with python 3.7
* classifier updated in setup py as python version 3.4, 3.7 added; also version increase for development.
* python 3.7 and 3.4 added in travis file
* fix: RST indentation at README.rst file
* changes log updated

### CODE REVIEW

**Review by mgedmin — APPROVED** [review]
LGTM.

Can you also add py34 through py37 to `tox.ini`?

**Review by mgedmin — APPROVED** [review]
LGTM.

BTW why is this marked [WIP]?  Do you have any further work planned on this branch?

**Comment by nazrulworld** [comment]
@mgedmin yes may be for example switch to semantic versioning #8

**Comment by mgedmin** [comment]
:sparkles: Thank you! :sparkles:

(Please update the pull request title and remove the WIP prefix before merging next time.)

**Pull request merged**
